<UI>:
    MDBoxLayout:
        orientation: 'vertical'
        MDLabel:
            text: "hello kivyMD"
            font_style: 'H2'
            halign: 'center'
           # color: '#FF0066'
           # theme_text_color: 'Custom'
            text_color: 0,0,1,1

        MDIcon:
            icon: "gmail"
            pos_hint: {"center_x": .5, "center_y": .5}
            color: "red"
