# Generated by Django 5.0.2 on 2024-02-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no1', models.CharField(max_length=1000, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('type1', models.CharField(choices=[('หนังสือ', 'หนังสือ'), ('นิตยสาร', 'นิตยสาร')], default='หนังสือ', max_length=20)),
                ('borrowingdate', models.DateField()),
                ('date_of_return', models.DateField()),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('addition_note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
