# Generated by Django 5.0.2 on 2024-03-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no1', models.CharField(max_length=1000, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('borrowingdate', models.DateField()),
                ('date_of_return', models.DateField()),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('addition_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no1', models.CharField(max_length=1000, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('borrowingdate', models.DateField()),
                ('date_of_return', models.DateField()),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('addition_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Borrow',
        ),
    ]
